# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81a7e6bbb0385f9d3fb3afbf954bba148df454e243df8150e0006e65fa799df051d434f08c4c690debe5a4bb5c340d3820923bfe0ee8e5829dbde3fd36335cef

test:
  secret_key_base: 4a4ab8f327829d874e231b60bb662f4db87c94d596c363709126273959de005e67eecd50a612e0c26f2d11bdb1daa72a9e8704ff4f4cf6695851f25632b7bbd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
